### ISSUE TITLE
Targetframe & FocusFrame - Buff/Castbar Anchoring Issue

### ISSUE THREAD

**Issue by G1t-Happens** [Daenarys/ClassicFrames#1]
Hi, @Daenarys 
If I simultaneously place two different players(probl npcs too ?) into the Target and Focus, the buffs as well as the castbars are jumping around/anchored incorrectly. Tested with latest v1.40

![Anchoring3](https://github.com/Daenarys/ClassicFrames/assets/44774729/144a24f0-3d57-47dc-9f8a-98c73977c056)

**Comment by Daenarys** [comment]
Thanks for the report, ill look into it.

**Comment by G1t-Happens** [comment]
@Daenarys 

Fixed it like in this: https://github.com/G1t-Happens/ClassicFrames/blob/main/skins/unitframes/TargetFrame.lua

**Comment by Daenarys** [comment]
fixed in v1.41
