### ISSUE TITLE
Only 5 combo points show when you have 7

### ISSUE THREAD

**Issue by Parquelle** [Daenarys/ClassicFrames#3]
As of 11.0, in the Assassination tree, you can select [Sanguine Stratagem](https://www.wowhead.com/spell=457512/sanguine-stratagem) as a talent, which adds another combo point. If you have already selected [Deeper Stratagem](https://www.wowhead.com/spell=193531/deeper-stratagem) in the Rogue tree, it will only display 5 combo points in your player frame, when you actually have 7.

**Comment by Daenarys** [comment]
fixed in v1.90
