### ISSUE TITLE
Objectives panel not updating

### ISSUE THREAD

**Issue by Snahkstrasza** [Daenarys/ClassicFrames#5]
The objectives panel seems to stop updating after some time, In this I was fighting Ragnaros in Searing Gorge but it still shows me to kill Leper Gnomes, I haven't observed base game objectives panel behaving like this
![Wow_zd9kiBur6r](https://github.com/user-attachments/assets/a13c51d3-a78c-4d99-86c3-efa157f71ded)
no lua errors or anything

**Comment by Daenarys** [comment]
probably a blizz issue
